export type BoardingFlow = "onboarding" | "offboarding";

export type PdfTable = {
  id: string;
  flow: BoardingFlow | "both";
  title: string;
  description?: string;
  /** Column headers, as represented in boardingdetails.pdf */
  columns: string[];
  /** Optional sample rows extracted from the PDF export */
  sampleRows?: Record<string, string>[];
  /** A best-effort column name to filter by selected employee */
  employeeNameColumn?: string;
};

/**
 * Source: boardingdetails.pdf (export of the operational workbook schema).
 * We treat this as the contract for UI tables (CRM-friendly view).
 */
export const BOARDING_PDF_TABLES: PdfTable[] = [
  {
    id: "offboarding-tracker",
    flow: "offboarding",
    title: "Offboarding Tracker",
    columns: ["Name", "Department", "Manager", "Last Day"],
    sampleRows: [
      {
        Name: "Minahil Tariq",
        Department: "Checkout",
        Manager: "Abdul Raheem",
        "Last Day": "29 January, 2026",
      },
      { Name: "Shanzay", Department: "Acquire", Manager: "Arman", "Last Day": "Immediate" },
    ],
    employeeNameColumn: "Name",
  },
  {
    id: "offboarding-form-responses",
    flow: "offboarding",
    title: "Offboarding Form Responses",
    description:
      "Operational confirmation of knowledge transfer + asset/access revocation (as captured in the PDF export).",
    columns: [
      "Name of Offboarded Employee",
      "Last working day",
      "Knowledge Transfer Completion Status",
      "Transfer Employee Drive Data to:",
      "Critical Assets and Access Revoked/Returned Status [Laptop/Computer]",
      "Critical Assets and Access Revoked/Returned Status [Mobile Phone/Tablet]",
      "Critical Assets and Access Revoked/Returned Status [Office Keys/Access Card]",
      "Critical Assets and Access Revoked/Returned Status [Software Licenses/Accounts]",
      "Critical Assets and Access Revoked/Returned Status [Team Drives/Shared Folder Access]",
      "Critical Assets and Access Revoked/Returned Status [Microsoft Teams]",
      "Critical Assets and Access Revoked/Returned Status [Time Doctor]",
      "Critical Assets and Access Revoked/Returned Status [Revcloud Email]",
      "Other Accounts Access That Needs to be Revoked (Please List)",
      "Performance Feedback/Exit Interview Scheduled?",
      "Manager's Overall Offboarding Satisfaction",
      "Any further comments or necessary actions?",
    ],
    employeeNameColumn: "Name of Offboarded Employee",
  },
  {
    id: "onboarding-form",
    flow: "onboarding",
    title: "Onboarding Form",
    description: "Day-0/Day-1 onboarding provisioning checklist fields (as exported in the PDF).",
    columns: [
      "Timestamp",
      "Employee Full Name",
      "Date of Joining",
      "Physical Resources and Access [Laptop Given]",
      "Physical Resources and Access [Access Card Issued]",
      "Physical Resources and Access [Parking Spot Allocated]",
      "Reporting Manager",
      "Account Provisioning Checklist [Google Account Setup]",
      "Account Provisioning Checklist [Time Doctor Account Setup]",
      "Account Provisioning Checklist [MS Team Account Setup]",
      "Account Provisioning Checklist [Slack Account Setup]",
      "Account Provisioning Checklist [JIRA Access Granted]",
      "Account Provisioning Checklist [Confluence Access Granted]",
      "Account Provisioning Checklist [AWS Access Granted]",
      "HR and Team Integration [Payroll Setup Completed]",
      "HR and Team Integration [Buddy Assigned]",
      "HR and Team Integration [Welcome Call Scheduled/Completed]",
      "Onboarding Coordinator/HR Representative Name",
      "Overall Onboarding Rating (out of 5)",
    ],
    employeeNameColumn: "Employee Full Name",
  },
  {
    id: "onboarding-mastersheet-short",
    flow: "onboarding",
    title: "Onboarding MasterSheet — Short",
    columns: [
      "Full Name",
      "Department",
      "Designation",
      "Date of Joining (DOJ)",
      "Sourcer",
      "Recruiter",
      "Candidate Docs Link",
      "Manager",
      "Team",
      "Active/Inactive",
      "Location",
      "Personal Email ID",
      "Phone Number",
      "Offer Letter Signed?",
      "Laptop Assigned?",
      "System Email Created?",
      "Buddy Assigned",
      "Orientation Date",
      "HR Checklist Complete?",
      "IT Checklist Complete? (Earpods/Laptop)",
      "Notes",
    ],
    employeeNameColumn: "Full Name",
  },
  {
    id: "active-list-employees",
    flow: "both",
    title: "Active List of all employees",
    columns: [
      "Name",
      "Cintara.ai Email",
      "Location",
      "Email ID",
      "Official Email",
      "Team",
      "Account Required?",
      "Password to use",
      "Status",
    ],
    employeeNameColumn: "Name",
  },
  {
    id: "30-60-90",
    flow: "onboarding",
    title: "30 / 60 / 90 Days Checklist",
    description: "Wide table (scroll horizontally). The PDF shows this as a single very wide checklist row model.",
    columns: [
      "Full Name",
      "Department",
      "Designation",
      "Date of Joining (DOJ)",
      "Recruiter",
      "Manager",
      "Team",
      "Location",
      "Email ID",
      "Phone Number",
      "Candidate Docs Link",
      "Offer Letter Signed",
      "Background Verification Completed",
      "NDA Signed",
      "Buddy Assigned",
      "T-Shirt Size (Onboarding Kit)",
      "Laptop provided",
      "System Access Provided",
      "Orientation Completed",
      "HR Introduction Completed",
      "First Week Schedule Shared",
      "Company Overview Session Attended",
      "Product Training Completed",
      "Office Space available",
      "Tools & Software Training Completed",
      "Role & Responsibilities Clarified",
      "Initial Goals Set",
      "First Week Feedback Collected",
      "Team Introduction Completed",
      "Organizational Chart Reviewed",
      "Compliance Training Completed",
      "Security Training Completed",
      "First Project Assigned",
      "First Project Completed",
      "1:1 with Manager Scheduled",
      "1:1 with Manager Completed",
      "Feedback from Manager Received (30 Days)",
      "Advanced Product Training Completed",
      "Cross-Functional Meetings Attended",
      "Mid-Point Review Scheduled",
      "Mid-Point Review Completed",
      "Feedback Implemented",
      "Participation in Team Meetings",
      "Second Project Assigned",
      "Second Project Completed",
      "Peer Feedback Collected",
      "Self-Assessment Completed",
      "Training Needs Identified",
      "Additional Training Provided",
      "Final Review Scheduled",
      "Final Review Completed",
      "Performance Evaluation Completed",
      "Confirmation of Role",
      "Long-Term Goals Set",
      "Career Development Plan Initiated",
      "Feedback from Manager Received (90 Days)",
      "Feedback from HR Received",
      "Feedback from Buddy Received",
      "Feedback from Peers Received",
      "Onboarding Survey Completed",
      "Onboarding Feedback Implemented",
      "Recognition/Award Received",
      "Added to Company Directory",
      "Company ID Card Issued",
      "Notes",
    ],
    employeeNameColumn: "Full Name",
  },
  {
    id: "buddy-manager-allotment",
    flow: "onboarding",
    title: "Buddy & Manager Allotment",
    description:
      "The PDF represents this as a 2-column table (Section, Details) repeated for each new joiner block.",
    columns: ["Section", "Details"],
  },
  {
    id: "offboarding-program",
    flow: "offboarding",
    title: "OffBoarding Program",
    description: "Stage-driven offboarding program table (SOP program as a table contract).",
    columns: ["Stage", "Action Item", "Owner", "Due Date", "Status"],
  },
];

