import type { BonusEmployee, BonusInputs } from "./types";

export const DEFAULT_BONUS_INPUTS: BonusInputs = {
  grossProfit: 500_000,
  bonusPoolPct: 5,
  splitTopPct: 60,
  splitGoodPct: 40,
  points: {
    topMgmt: 3,
    topEpd: 2,
    good: 1,
  },
};

export const MOCK_EMPLOYEES: BonusEmployee[] = [
  {
    id: "e_001",
    name: "Maya Thiru",
    email: "maya@acme.com",
    role: "VP Sales",
    team: "Revenue",
    baseSalary: 220_000,
    status: "ACTIVE",
    category: "TOP_MGMT",
    metrics: { teamLeadFeedback: 5, performanceScore: 92, okrScore: 0.9, workingHours: 520 },
  },
  {
    id: "e_002",
    name: "Jordan Lee",
    email: "jordan@acme.com",
    role: "Sales Manager",
    team: "Revenue",
    baseSalary: 165_000,
    status: "ACTIVE",
    category: "TOP_MGMT",
    metrics: { teamLeadFeedback: 4, performanceScore: 88, okrScore: 0.82, workingHours: 500 },
  },
  {
    id: "e_003",
    name: "Priya Nair",
    email: "priya@acme.com",
    role: "Growth Lead (EPD)",
    team: "Revenue",
    baseSalary: 150_000,
    status: "ACTIVE",
    category: "TOP_EPD",
    metrics: { teamLeadFeedback: 4, performanceScore: 85, okrScore: 0.78, workingHours: 510 },
  },
  {
    id: "e_004",
    name: "Alex Chen",
    email: "alex@acme.com",
    role: "Ops Manager",
    team: "Operations",
    baseSalary: 140_000,
    status: "ACTIVE",
    category: "TOP_EPD",
    metrics: { teamLeadFeedback: 4, performanceScore: 83, okrScore: 0.75, workingHours: 490 },
  },
  {
    id: "e_005",
    name: "Sam Rivera",
    email: "sam@acme.com",
    role: "HRBP",
    team: "Support",
    baseSalary: 110_000,
    status: "ACTIVE",
    category: "GOOD",
    metrics: { teamLeadFeedback: 4, performanceScore: 78, okrScore: 0.7, workingHours: 480 },
  },
  {
    id: "e_006",
    name: "Noah Patel",
    email: "noah@acme.com",
    role: "Analyst",
    team: "Operations",
    baseSalary: 95_000,
    status: "ACTIVE",
    category: "GOOD",
    metrics: { teamLeadFeedback: 3, performanceScore: 74, okrScore: 0.62, workingHours: 470 },
  },
  {
    id: "e_007",
    name: "Elena Gomez",
    email: "elena@acme.com",
    role: "Associate",
    team: "Support",
    baseSalary: 82_000,
    status: "PIP",
    category: "PIP",
    metrics: { teamLeadFeedback: 2, performanceScore: 55, okrScore: 0.41, workingHours: 430 },
  },
  {
    id: "e_008",
    name: "Omar Hassan",
    email: "omar@acme.com",
    role: "Coordinator",
    team: "Operations",
    baseSalary: 78_000,
    status: "NOTICE",
    category: "NOTICE",
    metrics: { teamLeadFeedback: 2, performanceScore: 58, okrScore: 0.45, workingHours: 410 },
  },
];

export const MOCK_PLANS = [
  {
    id: "bp_001",
    name: "Quarterly Variable Bonus",
    description: "Weighted pool allocation based on category points and eligibility.",
    cycle: "Q4",
    bonus_type: "variable_pool",
    active: true,
    pool_amount: null as number | null,
    formula: "TotalPool = GP * poolPct; Top/Good splits; point-based distribution; PIP/NOTICE = $0",
  },
  {
    id: "bp_002",
    name: "Revenue Accelerator (Draft)",
    description: "Higher weight for Revenue teams with guardrails and caps.",
    cycle: "Q4",
    bonus_type: "accelerator",
    active: false,
    pool_amount: null as number | null,
    formula: "Draft: base pool + revenue multiplier; cap at max_bonus_cap_pct",
  },
];

export const MOCK_APPROVALS = [
  { id: "ap_001", employeeId: "e_001", employee: "Maya Thiru", cycle: "Q4", approver_role: "MANAGER", status: "APPROVED", comments: "Outstanding quarter.", approved_at: "2026-04-10" },
  { id: "ap_002", employeeId: "e_001", employee: "Maya Thiru", cycle: "Q4", approver_role: "HR", status: "APPROVED", comments: "Eligible & in good standing.", approved_at: "2026-04-11" },
  { id: "ap_003", employeeId: "e_001", employee: "Maya Thiru", cycle: "Q4", approver_role: "FINANCE", status: "PENDING", comments: "", approved_at: null as string | null },
  { id: "ap_004", employeeId: "e_001", employee: "Maya Thiru", cycle: "Q4", approver_role: "CEO", status: "PENDING", comments: "", approved_at: null as string | null },
];

