/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TimeDashboardRouteImport } from './routes/time-dashboard'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as HelpRouteImport } from './routes/help'
import { Route as EquityRouteImport } from './routes/equity'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AlysonNotetakerRouteImport } from './routes/alyson-notetaker'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BonusRouteRouteImport } from './routes/bonus/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BonusIndexRouteImport } from './routes/bonus/index'
import { Route as TimeDashboardUserIdRouteImport } from './routes/time-dashboard.$userId'
import { Route as BonusSimulateRouteImport } from './routes/bonus/simulate'
import { Route as BonusPlansRouteImport } from './routes/bonus/plans'
import { Route as BonusAuditRouteImport } from './routes/bonus/audit'
import { Route as BonusApprovalsRouteImport } from './routes/bonus/approvals'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeDashboardRoute = TimeDashboardRouteImport.update({
  id: '/time-dashboard',
  path: '/time-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const EquityRoute = EquityRouteImport.update({
  id: '/equity',
  path: '/equity',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AlysonNotetakerRoute = AlysonNotetakerRouteImport.update({
  id: '/alyson-notetaker',
  path: '/alyson-notetaker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusRouteRoute = BonusRouteRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusIndexRoute = BonusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BonusRouteRoute,
} as any)
const TimeDashboardUserIdRoute = TimeDashboardUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => TimeDashboardRoute,
} as any)
const BonusSimulateRoute = BonusSimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => BonusRouteRoute,
} as any)
const BonusPlansRoute = BonusPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => BonusRouteRoute,
} as any)
const BonusAuditRoute = BonusAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => BonusRouteRoute,
} as any)
const BonusApprovalsRoute = BonusApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => BonusRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bonus': typeof BonusRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/alyson-notetaker': typeof AlysonNotetakerRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/equity': typeof EquityRoute
  '/help': typeof HelpRoute
  '/leave': typeof LeaveRoute
  '/payroll': typeof PayrollRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/time-dashboard': typeof TimeDashboardRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/bonus/approvals': typeof BonusApprovalsRoute
  '/bonus/audit': typeof BonusAuditRoute
  '/bonus/plans': typeof BonusPlansRoute
  '/bonus/simulate': typeof BonusSimulateRoute
  '/time-dashboard/$userId': typeof TimeDashboardUserIdRoute
  '/bonus/': typeof BonusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alyson-notetaker': typeof AlysonNotetakerRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/equity': typeof EquityRoute
  '/help': typeof HelpRoute
  '/leave': typeof LeaveRoute
  '/payroll': typeof PayrollRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/time-dashboard': typeof TimeDashboardRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/bonus/approvals': typeof BonusApprovalsRoute
  '/bonus/audit': typeof BonusAuditRoute
  '/bonus/plans': typeof BonusPlansRoute
  '/bonus/simulate': typeof BonusSimulateRoute
  '/time-dashboard/$userId': typeof TimeDashboardUserIdRoute
  '/bonus': typeof BonusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bonus': typeof BonusRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/alyson-notetaker': typeof AlysonNotetakerRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/equity': typeof EquityRoute
  '/help': typeof HelpRoute
  '/leave': typeof LeaveRoute
  '/payroll': typeof PayrollRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/time-dashboard': typeof TimeDashboardRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/bonus/approvals': typeof BonusApprovalsRoute
  '/bonus/audit': typeof BonusAuditRoute
  '/bonus/plans': typeof BonusPlansRoute
  '/bonus/simulate': typeof BonusSimulateRoute
  '/time-dashboard/$userId': typeof TimeDashboardUserIdRoute
  '/bonus/': typeof BonusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bonus'
    | '/admin'
    | '/alyson-notetaker'
    | '/attendance'
    | '/auth'
    | '/documents'
    | '/equity'
    | '/help'
    | '/leave'
    | '/payroll'
    | '/performance'
    | '/reports'
    | '/team'
    | '/time-dashboard'
    | '/workflows'
    | '/bonus/approvals'
    | '/bonus/audit'
    | '/bonus/plans'
    | '/bonus/simulate'
    | '/time-dashboard/$userId'
    | '/bonus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alyson-notetaker'
    | '/attendance'
    | '/auth'
    | '/documents'
    | '/equity'
    | '/help'
    | '/leave'
    | '/payroll'
    | '/performance'
    | '/reports'
    | '/team'
    | '/time-dashboard'
    | '/workflows'
    | '/bonus/approvals'
    | '/bonus/audit'
    | '/bonus/plans'
    | '/bonus/simulate'
    | '/time-dashboard/$userId'
    | '/bonus'
  id:
    | '__root__'
    | '/'
    | '/bonus'
    | '/admin'
    | '/alyson-notetaker'
    | '/attendance'
    | '/auth'
    | '/documents'
    | '/equity'
    | '/help'
    | '/leave'
    | '/payroll'
    | '/performance'
    | '/reports'
    | '/team'
    | '/time-dashboard'
    | '/workflows'
    | '/bonus/approvals'
    | '/bonus/audit'
    | '/bonus/plans'
    | '/bonus/simulate'
    | '/time-dashboard/$userId'
    | '/bonus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BonusRouteRoute: typeof BonusRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AlysonNotetakerRoute: typeof AlysonNotetakerRoute
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  DocumentsRoute: typeof DocumentsRoute
  EquityRoute: typeof EquityRoute
  HelpRoute: typeof HelpRoute
  LeaveRoute: typeof LeaveRoute
  PayrollRoute: typeof PayrollRoute
  PerformanceRoute: typeof PerformanceRoute
  ReportsRoute: typeof ReportsRoute
  TeamRoute: typeof TeamRoute
  TimeDashboardRoute: typeof TimeDashboardRouteWithChildren
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-dashboard': {
      id: '/time-dashboard'
      path: '/time-dashboard'
      fullPath: '/time-dashboard'
      preLoaderRoute: typeof TimeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equity': {
      id: '/equity'
      path: '/equity'
      fullPath: '/equity'
      preLoaderRoute: typeof EquityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alyson-notetaker': {
      id: '/alyson-notetaker'
      path: '/alyson-notetaker'
      fullPath: '/alyson-notetaker'
      preLoaderRoute: typeof AlysonNotetakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus': {
      id: '/bonus'
      path: '/bonus'
      fullPath: '/bonus'
      preLoaderRoute: typeof BonusRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus/': {
      id: '/bonus/'
      path: '/'
      fullPath: '/bonus/'
      preLoaderRoute: typeof BonusIndexRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/time-dashboard/$userId': {
      id: '/time-dashboard/$userId'
      path: '/$userId'
      fullPath: '/time-dashboard/$userId'
      preLoaderRoute: typeof TimeDashboardUserIdRouteImport
      parentRoute: typeof TimeDashboardRoute
    }
    '/bonus/simulate': {
      id: '/bonus/simulate'
      path: '/simulate'
      fullPath: '/bonus/simulate'
      preLoaderRoute: typeof BonusSimulateRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/bonus/plans': {
      id: '/bonus/plans'
      path: '/plans'
      fullPath: '/bonus/plans'
      preLoaderRoute: typeof BonusPlansRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/bonus/audit': {
      id: '/bonus/audit'
      path: '/audit'
      fullPath: '/bonus/audit'
      preLoaderRoute: typeof BonusAuditRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/bonus/approvals': {
      id: '/bonus/approvals'
      path: '/approvals'
      fullPath: '/bonus/approvals'
      preLoaderRoute: typeof BonusApprovalsRouteImport
      parentRoute: typeof BonusRouteRoute
    }
  }
}

interface BonusRouteRouteChildren {
  BonusApprovalsRoute: typeof BonusApprovalsRoute
  BonusAuditRoute: typeof BonusAuditRoute
  BonusPlansRoute: typeof BonusPlansRoute
  BonusSimulateRoute: typeof BonusSimulateRoute
  BonusIndexRoute: typeof BonusIndexRoute
}

const BonusRouteRouteChildren: BonusRouteRouteChildren = {
  BonusApprovalsRoute: BonusApprovalsRoute,
  BonusAuditRoute: BonusAuditRoute,
  BonusPlansRoute: BonusPlansRoute,
  BonusSimulateRoute: BonusSimulateRoute,
  BonusIndexRoute: BonusIndexRoute,
}

const BonusRouteRouteWithChildren = BonusRouteRoute._addFileChildren(
  BonusRouteRouteChildren,
)

interface TimeDashboardRouteChildren {
  TimeDashboardUserIdRoute: typeof TimeDashboardUserIdRoute
}

const TimeDashboardRouteChildren: TimeDashboardRouteChildren = {
  TimeDashboardUserIdRoute: TimeDashboardUserIdRoute,
}

const TimeDashboardRouteWithChildren = TimeDashboardRoute._addFileChildren(
  TimeDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BonusRouteRoute: BonusRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AlysonNotetakerRoute: AlysonNotetakerRoute,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  DocumentsRoute: DocumentsRoute,
  EquityRoute: EquityRoute,
  HelpRoute: HelpRoute,
  LeaveRoute: LeaveRoute,
  PayrollRoute: PayrollRoute,
  PerformanceRoute: PerformanceRoute,
  ReportsRoute: ReportsRoute,
  TeamRoute: TeamRoute,
  TimeDashboardRoute: TimeDashboardRouteWithChildren,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
